[package]
name = "rusty-svg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
convert_case = "0.8.0"
inquire = "0.7.5"
walkdir = "2.5.0"
